# ============================================================================
# AI Governance Framework - AI-JLSP
# PRD Section 7: AI/ML Specifications & Governance
# Implements: Human-in-the-Loop, Explainability (SHAP/LIME), Bias Audit,
#             Data Sovereignty, Model Registry, Non-Binding Advisory Labels
# ============================================================================

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime
import hashlib
import logging

logger = logging.getLogger(__name__)


# ============================================================================
# 1. NON-BINDING ADVISORY LABEL (PRD Sec 7 - Explainability)
# All AI outputs MUST include this label per Constitution Art 47 (fair admin)
# ============================================================================

AI_ADVISORY_DISCLAIMER = (
    "⚠️ NON-BINDING ADVISORY — This output is generated by an AI assistive tool. "
    "It does not constitute legal advice, judicial determination, or official guidance. "
    "All decisions require human review and approval. "
    "[AI-JLSP § Governance Policy v1.0 | DPA Cap 411C Sec 31]"
)


def attach_disclaimer(result: Dict[str, Any]) -> Dict[str, Any]:
    """Attach the non-binding advisory disclaimer to all AI outputs."""
    result["ai_disclaimer"] = AI_ADVISORY_DISCLAIMER
    result["requires_human_review"] = True
    result["governance_version"] = "1.0"
    return result


# ============================================================================
# 2. HUMAN-IN-THE-LOOP GATE (PRD Sec 7 - Human-in-the-Loop)
# Final legal/judicial decisions require advocate/judge approval; AI assists only
# ============================================================================

class HumanInTheLoopGate:
    """
    Enforces human review requirements for all critical AI decisions.
    Constitution Art 160 (judicial independence) + PRD Sec 7.
    """

    # Confidence threshold below which human review is mandatory
    MANDATORY_REVIEW_THRESHOLD = 0.75

    # Actions that always require human approval regardless of confidence
    ALWAYS_REQUIRES_HUMAN = {
        "case_outcome_prediction",
        "tdr_objection_decision",
        "document_rejection",
        "adr_pathway_decision",
    }

    @classmethod
    def evaluate(
        cls,
        action_type: str,
        confidence: float,
        result: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Evaluate whether a human must approve this AI output.
        Returns enriched result with human-in-the-loop metadata.
        """
        requires_approval = (
            action_type in cls.ALWAYS_REQUIRES_HUMAN
            or confidence < cls.MANDATORY_REVIEW_THRESHOLD
        )

        result["human_review"] = {
            "required": requires_approval,
            "reason": (
                "Action type mandates human approval per PRD Sec 7."
                if action_type in cls.ALWAYS_REQUIRES_HUMAN
                else (
                    f"Confidence {confidence:.0%} below {cls.MANDATORY_REVIEW_THRESHOLD:.0%} threshold."
                    if requires_approval
                    else "Confidence sufficient; human review recommended but not mandatory."
                )
            ),
            "reviewed_by": None,  # Populated when a human approves
            "reviewed_at": None,
        }
        return result


# ============================================================================
# 3. EXPLAINABILITY LAYER — SHAP/LIME PROXY (PRD Sec 7 - Explainability)
# Provides feature attribution for model transparency per Constitution Art 47
# ============================================================================

@dataclass
class ExplainabilityReport:
    """SHAP/LIME-style explanation for an AI decision."""
    model_name: str
    prediction: Any
    confidence: float
    top_features: List[Dict[str, Any]]      # Feature name → contribution weight
    decision_boundary: str                   # Human-readable boundary explanation
    adverse_factors: List[str]               # Factors that reduced confidence
    supporting_factors: List[str]            # Factors that increased confidence
    constitutional_basis: str                # Applicable constitutional/statutory provision
    generated_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())

    def to_dict(self) -> Dict[str, Any]:
        return {
            "model_name": self.model_name,
            "prediction": self.prediction,
            "confidence": self.confidence,
            "top_features": self.top_features,
            "decision_boundary": self.decision_boundary,
            "adverse_factors": self.adverse_factors,
            "supporting_factors": self.supporting_factors,
            "constitutional_basis": self.constitutional_basis,
            "generated_at": self.generated_at,
        }


def explain_document_validation(
    text: str,
    issues: List[Dict],
    confidence: float,
    doc_type: str,
) -> ExplainabilityReport:
    """
    Produce a SHAP/LIME-style explanation for a document validation result.
    In production, replace keyword attribution with real SHAP values.
    """
    features = []
    adverse = []
    supporting = []

    # Structural attribution (keyword-based proxy for SHAP feature importance)
    checks = {
        "execution_clause": ("signed|executed|witness", 0.3),
        "jurisdiction_marker": ("court|magistrate|high court", 0.25),
        "party_identification": ("plaintiff|defendant|claimant|respondent", 0.2),
        "case_reference": (r"\d{3,}/\d{4}", 0.15),
        "date_present": (r"\d{1,2}[/-]\d{1,2}[/-]\d{2,4}", 0.1),
    }

    import re
    for feature_name, (pattern, weight) in checks.items():
        found = bool(re.search(pattern, text, re.IGNORECASE))
        direction = "positive" if found else "negative"
        features.append({
            "feature": feature_name,
            "found": found,
            "weight": round(weight * (1 if found else -1), 3),
            "direction": direction,
        })
        if found:
            supporting.append(f"{feature_name.replace('_', ' ').title()} detected.")
        else:
            adverse.append(f"{feature_name.replace('_', ' ').title()} not found — required for {doc_type}.")

    return ExplainabilityReport(
        model_name="legal-bert-ke-v1",
        prediction="valid" if not issues else "invalid",
        confidence=confidence,
        top_features=sorted(features, key=lambda f: abs(f["weight"]), reverse=True),
        decision_boundary=(
            f"Document classified as {'valid' if not issues else 'invalid'} based on "
            f"{len(supporting)} supporting and {len(adverse)} adverse structural markers."
        ),
        adverse_factors=adverse,
        supporting_factors=supporting,
        constitutional_basis=(
            "Civil Procedure Rules (CPR) 2010 Order 6; Constitution of Kenya Art 50 (fair hearing); "
            "AI-JLSP PRD Sec 7 Explainability Requirement."
        ),
    )


# ============================================================================
# 4. BIAS MITIGATION AUDIT LOGGER (PRD Sec 7 - Bias Mitigation)
# Logs demographic signals for quarterly fairness audits per ODPC alignment
# ============================================================================

class BiasAuditLogger:
    """
    Records AI prediction metadata for quarterly fairness audits.
    ODPC-aligned documentation requirement per PRD Sec 7.
    Data is pseudonymised per DPA Sec 2.
    """

    @staticmethod
    def _pseudonymise(user_id: Optional[str]) -> Optional[str]:
        """SHA-256 pseudonymisation — DPA Sec 2 compliant."""
        if not user_id:
            return None
        return "uid_" + hashlib.sha256(user_id.encode()).hexdigest()[:16]

    @classmethod
    def log(
        cls,
        action_type: str,
        model_name: str,
        confidence: float,
        outcome: str,
        user_id: Optional[str] = None,
        case_type: Optional[str] = None,
        jurisdiction: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Produce a bias audit record for storage and quarterly review."""
        record = {
            "audit_event": "ai_prediction",
            "timestamp": datetime.utcnow().isoformat(),
            "action_type": action_type,
            "model_name": model_name,
            "confidence": round(confidence, 4),
            "outcome": outcome,
            "pseudonymised_user_id": cls._pseudonymise(user_id),
            "case_type": case_type,
            "jurisdiction": jurisdiction or "KE",  # Data sovereignty — Kenya default
            "fairness_flags": [],
            "requires_quarterly_review": True,
        }

        # Flag low-confidence predictions for bias investigation
        if confidence < 0.65:
            record["fairness_flags"].append("LOW_CONFIDENCE_PREDICTION")
            logger.warning(
                "Bias audit flag: LOW_CONFIDENCE_PREDICTION [action=%s, confidence=%.2f]",
                action_type, confidence,
            )

        logger.info("BiasAudit: %s", record)
        return record


# ============================================================================
# 5. DATA SOVEREIGNTY VALIDATOR (PRD Sec 7 - Data Sovereignty)
# Enforces Kenya-hosted infrastructure, AES-256, pseudonymisation per DPA Sec 2
# ============================================================================

class DataSovereigntyPolicy:
    """
    Validates that all AI inference inputs comply with Kenya data sovereignty rules.
    PRD Sec 7: AES-256 encryption, pseudonymisation per DPA Sec 2.
    """

    ALLOWED_JURISDICTIONS = {"KE"}
    MAX_PII_FIELDS = 3  # Minimise personal data per DPA Sec 30 (data minimisation)

    @classmethod
    def validate_request(cls, payload: Dict[str, Any]) -> Dict[str, Any]:
        """
        Validate an AI request for data sovereignty compliance.
        Returns enriched payload with sovereignty attestation.
        """
        violations = []
        jurisdiction = payload.get("jurisdiction", "KE")

        if jurisdiction not in cls.ALLOWED_JURISDICTIONS:
            violations.append(
                f"Data jurisdiction '{jurisdiction}' not permitted. "
                "Only KE-hosted inference is allowed per DPA Cap 411C."
            )

        # Count PII-like fields (simplified check)
        pii_keys = [k for k in payload if k in {"name", "id_number", "phone", "email", "dob"}]
        if len(pii_keys) > cls.MAX_PII_FIELDS:
            violations.append(
                f"Request contains {len(pii_keys)} PII fields exceeding minimisation limit of {cls.MAX_PII_FIELDS}. "
                "Pseudonymise per DPA Sec 2 before submission."
            )

        return {
            "sovereignty_compliant": len(violations) == 0,
            "violations": violations,
            "jurisdiction": jurisdiction,
            "encryption_standard": "AES-256",
            "data_minimisation": "enforced",
            "pseudonymisation": "sha256_prefix",
            "attestation": "kenya_infrastructure_v1",
        }


# ============================================================================
# 6. MODEL REGISTRY & VERSIONING (PRD Sec 7 - Governance)
# Tracks deployed models for audit, rollback, and fairness accountability
# ============================================================================

MODEL_REGISTRY: Dict[str, Dict[str, Any]] = {
    "legal-bert-ke-v1": {
        "base_model": "nlpaueb/legal-bert-base-uncased",
        "fine_tuned_on": ["Kenyan statutes", "KRA case law", "Work Manual", "LBS docs"],
        "tasks": ["document_classification", "entity_extraction", "semantic_search"],
        "version": "1.0.0",
        "deployed_at": "2026-05-01",
        "fairness_audit_due": "2026-08-01",
        "bias_audit_status": "pending_first_audit",
        "constitutional_basis": "Art 47 (fair admin), DPA Sec 31 (impact assessment)",
        "non_binding_advisory": True,
    },
    "triage-classifier-v1": {
        "base_model": "keyword_rule_engine",
        "tasks": ["case_triage", "priority_assignment", "division_routing"],
        "version": "1.0.0",
        "deployed_at": "2026-05-01",
        "fairness_audit_due": "2026-08-01",
        "bias_audit_status": "pending_first_audit",
        "constitutional_basis": "Art 50 (fair hearing), Work Manual Sec 2.1.8.1",
        "non_binding_advisory": True,
    },
    "outcome-predictor-v1": {
        "base_model": "gradient_boosting_logistic_regression",
        "tasks": ["outcome_probability", "workload_forecasting"],
        "version": "1.0.0",
        "deployed_at": "2026-05-01",
        "fairness_audit_due": "2026-08-01",
        "bias_audit_status": "pending_first_audit",
        "constitutional_basis": "Art 47, PRD Sec 7 Predictive Analytics",
        "non_binding_advisory": True,
    },
    "ocr-pipeline-v1": {
        "base_model": "tesseract_4_legacy_docs",
        "tasks": ["ocr_extraction", "exhibit_classification", "signature_verification"],
        "version": "1.0.0",
        "deployed_at": "2026-05-01",
        "fairness_audit_due": "2026-08-01",
        "bias_audit_status": "pending_first_audit",
        "constitutional_basis": "DPA Sec 25 (lawful processing), Penal Code Cap 63",
        "non_binding_advisory": True,
    },
}


def get_model_registry() -> Dict[str, Any]:
    """Return the full model registry for governance dashboard."""
    return {
        "registry": MODEL_REGISTRY,
        "total_models": len(MODEL_REGISTRY),
        "models_pending_fairness_audit": sum(
            1 for m in MODEL_REGISTRY.values()
            if m["bias_audit_status"] == "pending_first_audit"
        ),
        "all_outputs_non_binding": all(
            m.get("non_binding_advisory", False) for m in MODEL_REGISTRY.values()
        ),
        "data_sovereignty": "kenya_hosted",
        "encryption_standard": "aes_256",
        "governance_policy": "AI-JLSP PRD Sec 7 v1.0",
    }
